ifeq ($(CONFIG_SEC_A25),y)
subdir-y += a25x
else ifeq ($(CONFIG_SEC_A33),y)
subdir-y += a33x
else ifeq ($(CONFIG_SEC_A53),y)
subdir-y += a53x
else ifeq ($(CONFIG_SEC_P62),y)
subdir-y += gta4xls
subdir-y += gta4xlswifi
else ifeq ($(CONFIG_SEC_M33),y)
subdir-y += m33x
else ifeq ($(CONFIG_SEC_M34),y)
subdir-y += m34x
endif
