# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_EXYNOS) += \
	s5e8825-erd8825.dtbo     \
	s5e8825-erd8825_r10.dtbo \
	s5e8825-erd8825_r11.dtbo

always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
