name: Build UN1CA Kernel

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'sixteen'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_RO_BUILD_KERNEL }}

      - name: Checkout build repository
        run: |
          git clone --depth=1 --recurse-submodules "git@github.com:majaahh/build-kernel.git" "build"

      - name: Free disk space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Install dependencies
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
              brotli zip zstd tar lz4 cpio xz-utils flex \
              bc kmod ccache binutils-aarch64-linux-gnu

      - name: Build
        id: build
        run: |
          [[ -f "./build/build.sh" ]] && ./build/build.sh || exit 1
          git pull origin ${{github.ref}} --ff-only
          FILE=$(ls build/builds/UN1CA_Kernel-*-a53x.tar | head -n 1)
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "tag=${FILE#build/builds/}" | sed 's/\.tar$//' >> "$GITHUB_OUTPUT"
          git tag "${FILE%.tar}"

      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          name: ${{ steps.build.outputs.tag }}
          body: |
            - Branch: `${{ github.ref_name }}`
            - Commit: `${{ github.sha }}`
          files: |
            ${{ steps.build.outputs.file }}
